name: "Pre-review Tests"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      CUPY_CI: GitHub

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # cupyx.array_api uses Python 3.8 syntaxes
        python-version: '3.8'

    - name: Build
      run: |
        pip install -U pip wheel
        pip install cython
        READTHEDOCS=True pip install -U -e .[stylecheck]

    - name: Coding Style (flake8)
      run: |
        flake8
        flake8 --config=.flake8.cython

    - name: Coding Style (autopep8)
      run: |
        autopep8 -r . --diff | tee check_autopep8
        test ! -s check_autopep8

    - name: Test - Docs Build
      run: |
        # Test to detect invalid escape sequences in docstrings (#1619)
        python -Werror::DeprecationWarning -m compileall -f -q cupy cupyx examples tests docs
        pushd docs
        pip install -r requirements.txt
        SPHINXOPTS=-W make html
        popd

    - name: Test - Installer
      run: |
        pip install mypy
        pushd install
        mypy cupy_builder

    - name: Test - CI Generator
      run: |
        pip install PyYAML types-PyYAML mypy
        pushd .pfnci
        ./generate.py --matrix matrix.yaml --schema schema.yaml --dry-run
        mypy generate.py
        popd

  rocm-build:
    runs-on: ubuntu-18.04
    env:
      CUPY_CI: "GitHub"
      ROCM_REPO: "4.3.1"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Setup ROCm
      run: |
        wget -qO - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
        echo "deb [arch=amd64] http://repo.radeon.com/rocm/apt/${ROCM_REPO}/ ubuntu main" | sudo tee /etc/apt/sources.list.d/rocm.list
        sudo apt-get -qqy update
        sudo apt-get -qqy install rocm-dev hipblas hipfft hipsparse rocsparse rocrand rocthrust rocsolver rocfft hipcub rocprim rccl

        echo "ROCM_HOME=/opt/rocm" >> "${GITHUB_ENV}"
        echo "PATH=${ROCM_HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
        echo "LD_LIBRARY_PATH=${ROCM_HOME}/lib:${LD_LIBRARY_PATH}" >> "${GITHUB_ENV}"

        hipconfig

    - name: Build
      run: |
        pip install -U pip wheel
        pip install cython

        export HCC_AMDGPU_TARGET=gfx900
        export CUPY_INSTALL_USE_HIP=1
        pip install -U -e .

    - name: Test Import
      run: |
        pushd /
        python -c "import cupy; cupy.show_config()"
        popd
